FROM registry.access.redhat.com/ubi9/python-311:1@sha256:31ca5e9a7381a1cecf40e774eef478de40ba41f51fc77127954ed33f97e59ed9

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# modify permissions to support running with a random uid
RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json

LABEL com.redhat.component="odh-feature-server" \
      name="odh-feature-server-rhel9" \
      description="odh-feature-server" \
      summary="odh-feature-server" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-feature-server" \
      io.k8s.description="odh-feature-server"